package com.chengjs.cjsssmweb.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SysUserExample {
  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database table sys_user
   *
   * @mbggenerated
   */
  protected String orderByClause;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database table sys_user
   *
   * @mbggenerated
   */
  protected boolean distinct;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database table sys_user
   *
   * @mbggenerated
   */
  protected List<Criteria> oredCriteria;

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table sys_user
   *
   * @mbggenerated
   */
  public SysUserExample() {
    oredCriteria = new ArrayList<Criteria>();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table sys_user
   *
   * @mbggenerated
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table sys_user
   *
   * @mbggenerated
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table sys_user
   *
   * @mbggenerated
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table sys_user
   *
   * @mbggenerated
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table sys_user
   *
   * @mbggenerated
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table sys_user
   *
   * @mbggenerated
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table sys_user
   *
   * @mbggenerated
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table sys_user
   *
   * @mbggenerated
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table sys_user
   *
   * @mbggenerated
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table sys_user
   *
   * @mbggenerated
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  /**
   * This class was generated by MyBatis Generator.
   * This class corresponds to the database table sys_user
   *
   * @mbggenerated
   */
  protected abstract static class GeneratedCriteria {
    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    public Criteria andIdIsNull() {
      addCriterion("id is null");
      return (Criteria) this;
    }

    public Criteria andIdIsNotNull() {
      addCriterion("id is not null");
      return (Criteria) this;
    }

    public Criteria andIdEqualTo(String value) {
      addCriterion("id =", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotEqualTo(String value) {
      addCriterion("id <>", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdGreaterThan(String value) {
      addCriterion("id >", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdGreaterThanOrEqualTo(String value) {
      addCriterion("id >=", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdLessThan(String value) {
      addCriterion("id <", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdLessThanOrEqualTo(String value) {
      addCriterion("id <=", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdLike(String value) {
      addCriterion("id like", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotLike(String value) {
      addCriterion("id not like", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdIn(List<String> values) {
      addCriterion("id in", values, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotIn(List<String> values) {
      addCriterion("id not in", values, "id");
      return (Criteria) this;
    }

    public Criteria andIdBetween(String value1, String value2) {
      addCriterion("id between", value1, value2, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotBetween(String value1, String value2) {
      addCriterion("id not between", value1, value2, "id");
      return (Criteria) this;
    }

    public Criteria andNameIsNull() {
      addCriterion("name is null");
      return (Criteria) this;
    }

    public Criteria andNameIsNotNull() {
      addCriterion("name is not null");
      return (Criteria) this;
    }

    public Criteria andNameEqualTo(String value) {
      addCriterion("name =", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameNotEqualTo(String value) {
      addCriterion("name <>", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameGreaterThan(String value) {
      addCriterion("name >", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameGreaterThanOrEqualTo(String value) {
      addCriterion("name >=", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameLessThan(String value) {
      addCriterion("name <", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameLessThanOrEqualTo(String value) {
      addCriterion("name <=", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameLike(String value) {
      addCriterion("name like", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameNotLike(String value) {
      addCriterion("name not like", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameIn(List<String> values) {
      addCriterion("name in", values, "name");
      return (Criteria) this;
    }

    public Criteria andNameNotIn(List<String> values) {
      addCriterion("name not in", values, "name");
      return (Criteria) this;
    }

    public Criteria andNameBetween(String value1, String value2) {
      addCriterion("name between", value1, value2, "name");
      return (Criteria) this;
    }

    public Criteria andNameNotBetween(String value1, String value2) {
      addCriterion("name not between", value1, value2, "name");
      return (Criteria) this;
    }

    public Criteria andRoleIdIsNull() {
      addCriterion("role_id is null");
      return (Criteria) this;
    }

    public Criteria andRoleIdIsNotNull() {
      addCriterion("role_id is not null");
      return (Criteria) this;
    }

    public Criteria andRoleIdEqualTo(String value) {
      addCriterion("role_id =", value, "roleId");
      return (Criteria) this;
    }

    public Criteria andRoleIdNotEqualTo(String value) {
      addCriterion("role_id <>", value, "roleId");
      return (Criteria) this;
    }

    public Criteria andRoleIdGreaterThan(String value) {
      addCriterion("role_id >", value, "roleId");
      return (Criteria) this;
    }

    public Criteria andRoleIdGreaterThanOrEqualTo(String value) {
      addCriterion("role_id >=", value, "roleId");
      return (Criteria) this;
    }

    public Criteria andRoleIdLessThan(String value) {
      addCriterion("role_id <", value, "roleId");
      return (Criteria) this;
    }

    public Criteria andRoleIdLessThanOrEqualTo(String value) {
      addCriterion("role_id <=", value, "roleId");
      return (Criteria) this;
    }

    public Criteria andRoleIdLike(String value) {
      addCriterion("role_id like", value, "roleId");
      return (Criteria) this;
    }

    public Criteria andRoleIdNotLike(String value) {
      addCriterion("role_id not like", value, "roleId");
      return (Criteria) this;
    }

    public Criteria andRoleIdIn(List<String> values) {
      addCriterion("role_id in", values, "roleId");
      return (Criteria) this;
    }

    public Criteria andRoleIdNotIn(List<String> values) {
      addCriterion("role_id not in", values, "roleId");
      return (Criteria) this;
    }

    public Criteria andRoleIdBetween(String value1, String value2) {
      addCriterion("role_id between", value1, value2, "roleId");
      return (Criteria) this;
    }

    public Criteria andRoleIdNotBetween(String value1, String value2) {
      addCriterion("role_id not between", value1, value2, "roleId");
      return (Criteria) this;
    }

    public Criteria andCreatetimeIsNull() {
      addCriterion("createtime is null");
      return (Criteria) this;
    }

    public Criteria andCreatetimeIsNotNull() {
      addCriterion("createtime is not null");
      return (Criteria) this;
    }

    public Criteria andCreatetimeEqualTo(Date value) {
      addCriterion("createtime =", value, "createtime");
      return (Criteria) this;
    }

    public Criteria andCreatetimeNotEqualTo(Date value) {
      addCriterion("createtime <>", value, "createtime");
      return (Criteria) this;
    }

    public Criteria andCreatetimeGreaterThan(Date value) {
      addCriterion("createtime >", value, "createtime");
      return (Criteria) this;
    }

    public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
      addCriterion("createtime >=", value, "createtime");
      return (Criteria) this;
    }

    public Criteria andCreatetimeLessThan(Date value) {
      addCriterion("createtime <", value, "createtime");
      return (Criteria) this;
    }

    public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
      addCriterion("createtime <=", value, "createtime");
      return (Criteria) this;
    }

    public Criteria andCreatetimeIn(List<Date> values) {
      addCriterion("createtime in", values, "createtime");
      return (Criteria) this;
    }

    public Criteria andCreatetimeNotIn(List<Date> values) {
      addCriterion("createtime not in", values, "createtime");
      return (Criteria) this;
    }

    public Criteria andCreatetimeBetween(Date value1, Date value2) {
      addCriterion("createtime between", value1, value2, "createtime");
      return (Criteria) this;
    }

    public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
      addCriterion("createtime not between", value1, value2, "createtime");
      return (Criteria) this;
    }

    public Criteria andModifytimeIsNull() {
      addCriterion("modifytime is null");
      return (Criteria) this;
    }

    public Criteria andModifytimeIsNotNull() {
      addCriterion("modifytime is not null");
      return (Criteria) this;
    }

    public Criteria andModifytimeEqualTo(Date value) {
      addCriterion("modifytime =", value, "modifytime");
      return (Criteria) this;
    }

    public Criteria andModifytimeNotEqualTo(Date value) {
      addCriterion("modifytime <>", value, "modifytime");
      return (Criteria) this;
    }

    public Criteria andModifytimeGreaterThan(Date value) {
      addCriterion("modifytime >", value, "modifytime");
      return (Criteria) this;
    }

    public Criteria andModifytimeGreaterThanOrEqualTo(Date value) {
      addCriterion("modifytime >=", value, "modifytime");
      return (Criteria) this;
    }

    public Criteria andModifytimeLessThan(Date value) {
      addCriterion("modifytime <", value, "modifytime");
      return (Criteria) this;
    }

    public Criteria andModifytimeLessThanOrEqualTo(Date value) {
      addCriterion("modifytime <=", value, "modifytime");
      return (Criteria) this;
    }

    public Criteria andModifytimeIn(List<Date> values) {
      addCriterion("modifytime in", values, "modifytime");
      return (Criteria) this;
    }

    public Criteria andModifytimeNotIn(List<Date> values) {
      addCriterion("modifytime not in", values, "modifytime");
      return (Criteria) this;
    }

    public Criteria andModifytimeBetween(Date value1, Date value2) {
      addCriterion("modifytime between", value1, value2, "modifytime");
      return (Criteria) this;
    }

    public Criteria andModifytimeNotBetween(Date value1, Date value2) {
      addCriterion("modifytime not between", value1, value2, "modifytime");
      return (Criteria) this;
    }

    public Criteria andDiscardIsNull() {
      addCriterion("discard is null");
      return (Criteria) this;
    }

    public Criteria andDiscardIsNotNull() {
      addCriterion("discard is not null");
      return (Criteria) this;
    }

    public Criteria andDiscardEqualTo(String value) {
      addCriterion("discard =", value, "discard");
      return (Criteria) this;
    }

    public Criteria andDiscardNotEqualTo(String value) {
      addCriterion("discard <>", value, "discard");
      return (Criteria) this;
    }

    public Criteria andDiscardGreaterThan(String value) {
      addCriterion("discard >", value, "discard");
      return (Criteria) this;
    }

    public Criteria andDiscardGreaterThanOrEqualTo(String value) {
      addCriterion("discard >=", value, "discard");
      return (Criteria) this;
    }

    public Criteria andDiscardLessThan(String value) {
      addCriterion("discard <", value, "discard");
      return (Criteria) this;
    }

    public Criteria andDiscardLessThanOrEqualTo(String value) {
      addCriterion("discard <=", value, "discard");
      return (Criteria) this;
    }

    public Criteria andDiscardLike(String value) {
      addCriterion("discard like", value, "discard");
      return (Criteria) this;
    }

    public Criteria andDiscardNotLike(String value) {
      addCriterion("discard not like", value, "discard");
      return (Criteria) this;
    }

    public Criteria andDiscardIn(List<String> values) {
      addCriterion("discard in", values, "discard");
      return (Criteria) this;
    }

    public Criteria andDiscardNotIn(List<String> values) {
      addCriterion("discard not in", values, "discard");
      return (Criteria) this;
    }

    public Criteria andDiscardBetween(String value1, String value2) {
      addCriterion("discard between", value1, value2, "discard");
      return (Criteria) this;
    }

    public Criteria andDiscardNotBetween(String value1, String value2) {
      addCriterion("discard not between", value1, value2, "discard");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator.
   * This class corresponds to the database table sys_user
   *
   * @mbggenerated do_not_delete_during_merge
   */
  public static class Criteria extends GeneratedCriteria {

    protected Criteria() {
      super();
    }
  }

  /**
   * This class was generated by MyBatis Generator.
   * This class corresponds to the database table sys_user
   *
   * @mbggenerated
   */
  public static class Criterion {
    private String condition;

    private Object value;

    private Object secondValue;

    private boolean noValue;

    private boolean singleValue;

    private boolean betweenValue;

    private boolean listValue;

    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }
}